-- DEVELOPMENT/TESTING ONLY

DROP TABLE IF EXISTS menu_items;

CREATE TABLE menu_items (
	id SERIAL PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	description VARCHAR(100) NOT NULL,
	price NUMERIC(5,2) NOT NULL CHECK (price >= 0),
	category VARCHAR(20) NOT NULL,
	image_url TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);