services:
    db:
        image: postgres:15
        container_name: pizza-postgres
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./api/db/init/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
            - ./api/db/init/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
            - ./api/db/init/init.sql:/docker-entrypoint-initdb.d/init.sql

    api:
        build: ./api
        container_name: pizza-api
        restart: always
        env_file:
            - .env
        ports:
            - "5000:5000"
        depends_on:
            - db

    client:
        build: ./client
        container_name: pizza-client
        env_file:
            - .env
        ports:
            - "5173:5173"
        depends_on:
            - api

volumes:
    pgdata:
